AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Sample infrastructure template for demonstrating
  IAM Access Analyzer policy validation in CI/CD.

Resources:

  DemoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: iam-access-analyzer-demo-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: DemoPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                Resource: '*'